title: jjsilvera # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data analyst, data tech, big data, inform√°tico
  <br><br>
  Second description 
  <br><br>
  <a href="https://github.com/jjsilvera">GitHub</a>
  <a href="https://linkedin.com/in/jairo-silvera-sarmiento">LinkedIn</a>
  <a href="https://twitter.com/joroilver">Twitter</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
